# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Disabled June 02, 2018
# cache:
#  - C:\RLibrary

# Adapt as necessary starting from here

# >>> Added June 02, 2018
environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true

  matrix:
# Does not work (some unit tests produce slightliy different results on Windows - possibly due to different semantics)
#  - R_VERSION: 3.2.0
#    R_ARCH: x64
#    CRAN: http://cran.rstudio.com
    
  - R_VERSION: devel
    GCC_PATH: mingw_32

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: stable

  - R_VERSION: patched
    R_ARCH: x64

  - R_VERSION: oldrel
    CRAN: http://cran.rstudio.com


# Too old to make the testthat unit tests working on this R version
#  - R_VERSION: 3.1.3
#    RTOOLS_VERSION: 32
#    CRAN: http://cran.rstudio.com

# Too old to make the testthat unit tests working on this R version
#  - R_VERSION: 3.1.0
#    RTOOLS_VERSION: 32
#    GCC_PATH: mingw_32
#    CRAN: http://cran.rstudio.com
#    PKGTYPE: source

matrix:
  fast_finish: true

# <<< end of "added"

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
