# DO NOT CHANGE the "init" and "install" sections below

# For details see:
# https://github.com/krlmlr/r-appveyor

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Disabled June 02, 2018
# cache:
#  - C:\RLibrary

# Adapt as necessary starting from here

# >>> Added June 02, 2018
environment:
  global:
    # WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true
    # uses binary packages if available otherwise source packages
    # important for devel build which may lack binary packages causing the CI builds to fail quite early (fast_finish: true)
    # Note: Using source packages only may increase the build time massively
    PKGTYPE: both
    # DISABLED SINCE IT DOES NOT WORK (still build errors due to missing "suggested" packages like testthat)
    #
    # Avoids errors of the form "Package suggested but not available" when executing
    #   R CMD check tryCatchLog.tar.gz --no-manual --as-cran --install-args=--build
    # Packages suggested but not available:
    #   'futile.logger', 'testthat', 'knitr', 'rmarkdown', 'covr'
    # The suggested packages are required for a complete check.
    # _R_CHECK_FORCE_SUGGESTS_: false


  matrix:
# Does not work (some unit tests produce slightliy different results on Windows - possibly due to different semantics)
#  - R_VERSION: 3.2.0
#    R_ARCH: x64
#    CRAN: http://cran.rstudio.com

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: stable

  - R_VERSION: patched
    R_ARCH: x64

  - R_VERSION: oldrel
    CRAN: http://cran.rstudio.com

# build the devel versions as last jobs (otherwise matrix "fast_finish: true" would stop
# when the devel version makes problems like missing packages even though
# the non-devel versions would build successfully)

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64
    PKGTYPE: binary
    # "binary" is workaround since appveyor does not find the packages otherwise

  - R_VERSION: devel
    GCC_PATH: mingw_32

# Too old to make the testthat unit tests working on this R version
#  - R_VERSION: 3.1.3
#    RTOOLS_VERSION: 32
#    CRAN: http://cran.rstudio.com

# Too old to make the testthat unit tests working on this R version
#  - R_VERSION: 3.1.0
#    RTOOLS_VERSION: 32
#    GCC_PATH: mingw_32
#    CRAN: http://cran.rstudio.com
#    PKGTYPE: source

matrix:
  fast_finish: false

# <<< end of "added"

# To install packages manuall you could add:
# - travis-tool.sh install_github RDatatable/data.table
# - travis-tool.sh install_github hadley/devtools
# - travis-tool.sh install_r ggplot2
build_script:
# install_deps should always work - no need to install suggested packages manually...
#  - travis-tool.sh install_r covr
#  - travis-tool.sh install_r testthat
#  - travis-tool.sh install_r knitr
#  - travis-tool.sh install_r rmarkdown
#  - travis-tool.sh install_r futile.logger
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
